/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Feature#getFun <em>Fun</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Feature#getComp <em>Comp</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Feature#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Feature#getValuereturn <em>Valuereturn</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFeature()
 * @model
 * @generated
 */
public interface Feature extends EObject
{
  /**
   * Returns the value of the '<em><b>Fun</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fun</em>' attribute.
   * @see #setFun(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFeature_Fun()
   * @model
   * @generated
   */
  String getFun();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Feature#getFun <em>Fun</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fun</em>' attribute.
   * @see #getFun()
   * @generated
   */
  void setFun(String value);

  /**
   * Returns the value of the '<em><b>Comp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comp</em>' attribute.
   * @see #setComp(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFeature_Comp()
   * @model
   * @generated
   */
  String getComp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Feature#getComp <em>Comp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comp</em>' attribute.
   * @see #getComp()
   * @generated
   */
  void setComp(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFeature_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Feature#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Valuereturn</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valuereturn</em>' attribute.
   * @see #setValuereturn(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFeature_Valuereturn()
   * @model
   * @generated
   */
  int getValuereturn();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Feature#getValuereturn <em>Valuereturn</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valuereturn</em>' attribute.
   * @see #getValuereturn()
   * @generated
   */
  void setValuereturn(int value);

} // Feature
