/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.massi.melangeuse.ui.internal.MelangeuseActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MelangeuseActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
