/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Scan;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Scan</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ScanImpl extends FeatureImpl implements Scan
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScanImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SCAN;
  }

} //ScanImpl
