/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Shut;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Shut</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ShutImpl extends FeatureImpl implements Shut
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ShutImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SHUT;
  }

} //ShutImpl
